### Login
POST https://auth.arorms.cn/realms/arorms/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = password &
client_id = email-react &
username = {{username}} &
password = {{password}}